.TH "lfsdock" "1" "0.2.0" "K.D.Hedger" "User Commands"
.SH "NAME"
\fBlfsdock\fR - Manual page for lfspanel.
.br
.SH "SYNOPSIS"
\fBlfsdock\fR DOCKID
.br

.SH "DESCRIPTION"
Part of the LFS Desktop  project here:
.br

https://github.com/KeithDHedger/LFSDesktopProject
.br

This provides basic dock functionality, calandar, launchers, clock, taskbar, desktop switcher, volume slider (alsa).
.br
.SH "EXAMPLES"
Start new main lfsdock using config file ~/.config/LFS/lfsdock.rc 
.br
	lfsdock
.br

Start new lfsdock using config file ~/.config/LFS/lfsdock-PROJECTS.rc
.br
	lfspanel PROJECTS
.br

Start new lfsdock using config file ~/.config/LFS/lfsdock-DEV.rc 
.br
	lfsdock DEV
.br

.SH "FILES"
Sample rc file:
.br

font Arial:size=10
.br
usebg true
.br
dockgrav 2
.br
docksize 2
.br
onmonitor 1
.br
usebgpath /home/keithhedger/Backgrounds/wood.png
.br
textcolour #FF000000
.br
gadgetsleft cssssLCDssssT
.br
refreshrate 1000000
.br
termcommand kkterminal -m -l -e
.br
dockbgcolour #E6C3C3C3
.br
prelightcolour #00000000
.br
usemicroseconds true
.br

You should use the lfsdockprefs applcation.
.br
.SH "REPORTING BUGS"
Report bugs to keithdhedger@gmail.com
.br
