.\" kkeditqt
.TH "kkeditqt" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
kkeditqt \- manual page for kkeditqt 0.0.0
.SH "SYNOPSIS"
.B kkeditqt
.SH "DESCRIPTION"
A GUI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
kkeditqt
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
