#!/bin/bash -e

#
#©K. D. Hedger. Tue 31 Jul 13:17:03 BST 2018 keithdhedger@gmail.com
#
#This file (lfslaunchpanels) is part of LFSApplications.
#
#LFSApplications is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#at your option) any later version.
#
#LFSApplications is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with LFSApplications.  If not, see <http://www.gnu.org/licenses/>.
#


lfspanel &
while read
	do
		rcfile=$(basename $REPLY .rc)
		rcfile=${rcfile##?*-}
		if [ "X$rcfile" != "Xlfspanel" ];then
			lfspanel $rcfile &
		fi
	done < <(ls -1 ~/.config/LFS/lfspanel*)