#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Deletes all lines starting with a comment mark '#' in selection.

echo -n "$KKEDIT_SELECTION"|sed -e '/^\s*#/d'
