#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Shows file encoding, requires zenity or yad, always shows in popup and needs no selection.
CHARSET="$(file -bi "$KKEDIT_CURRENTFILE"|awk -F "=" '{print $2}')"
zenity --info title="File Encoding" --text="The encoding of this file is:\n<big><b>"$CHARSET"</b></big>"
