#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Deletes all lines in selection starting with a comment '#'
#Renamed tool to "Delete Comments"

echo -n "$KKEDIT_SELECTION"|sed -e '/^\s*#/d'

#Original script:
#echo -n "$KKEDIT_SELECTION"|sed -e '/^\s*#/d'
