#!/bin/bash -e

#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#
#Removes blank lines from selected text.

echo -n "$KKEDIT_SELECTION"|sed -e '/^\s*$/d'
