#!/bin/bash -e

#Adapted from Document Statistics tool in medit
#Submitted by:
#©Sadi Yumuşak <sadiyumusak@gmail.com>
#All comments and suggestions to the above.
#Script and tools options may have been tweaked by me.
#This script was combined with the 'File Encoding' script also submitted by Sadi.
#
#Shows document information, always shows in popup and needs no selection.

bytes=$( wc -c  "$KKEDIT_CURRENTFILE")
chars=$( wc -m  "$KKEDIT_CURRENTFILE")
words=$( wc -w  "$KKEDIT_CURRENTFILE")
lines=$( wc -l  "$KKEDIT_CURRENTFILE")
lngst=$( wc -L  "$KKEDIT_CURRENTFILE")
CHARSET="$(file -bi "$KKEDIT_CURRENTFILE"|awk -F "=" '{print $2}')"

echo
echo "File size: ${bytes%% *}"
echo "Characters: ${chars%% *}"
echo "Words: ${words%% *}"
echo "Lines: ${lines%% *}"
echo "Longest Line: ${lngst%% *}"
echo "File Encoding: $CHARSET" 
echo "Filepath: $KKEDIT_CURRENTFILE"
echo 
