#!/bin/bash -e

#©keithhedger Thu 5 Sep 13:39:19 BST 2013 kdhedger68713@gmail.com

case $KKEDIT_SOURCE_LANG in
	"sh")
		COMMENTCHARS="#"
		COMMENTLEN=1
		;;
	"C++"|"C"|"Objective-C"|"C/C++/ObjC Header")
		COMMENTCHARS="//"
		COMMENTLEN=2
		;;
	*)
		echo -n "${KKEDIT_SELECTION}"
		exit 0
		;;
esac

if [ "${KKEDIT_SELECTION:0:$COMMENTLEN}" != "${COMMENTCHARS:0:$COMMENTLEN}" ];then
	while read
		do
			echo "${COMMENTCHARS}${REPLY}"

		done < <(echo -n "${KKEDIT_SELECTION}")
else
	while read
		do
			if [ ${REPLY:0:$COMMENTLEN} = "${COMMENTCHARS:0:$COMMENTLEN}" ];then
				echo "${REPLY#"${COMMENTCHARS}"}"
			else
				echo $REPLY
			fi
		done < <(echo -en "${KKEDIT_SELECTION}")
fi 
