#!/bin/bash -e

#©keithhedger Sun 5 May 18:32:13 BST 2013 kdhedger68713@gmail.com

BASE=$(yad --entry --entry-label="File Name:" --title="Select File Name")

echo "/******************************************************" > "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "*" >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "*     ©$USER $(date)" >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "*     kdhedger68713@gmail.com" >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "*" >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "*     ${BASE}.cpp" >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "* " >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"
echo "******************************************************/" >> "${KKEDIT_CURRENTDIR}/${BASE}.cpp"

echo "/******************************************************" > "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "*" >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "*     ©$USER $(date)" >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "*     kdhedger68713@gmail.com" >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "*" >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "*     ${BASE}.h" >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "* " >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "******************************************************/" >> "${KKEDIT_CURRENTDIR}/${BASE}.h"

UPPERBASE=$(echo ${BASE}|tr [a-z] [A-Z])
echo >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "#ifndef _${UPPERBASE}_">> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo "#define _${UPPERBASE}_">> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo >> "${KKEDIT_CURRENTDIR}/${BASE}.h"
echo >> "${KKEDIT_CURRENTDIR}/${BASE}.h"

echo "#endif">> "${KKEDIT_CURRENTDIR}/${BASE}.h"
