.TH "LFSApplications" "1" "0.0.4" "K.D.Hedger" "User Commands"
.SH "NAME"
\fBLFSApplications\fR - Manual page for lfsapplications.
.br

.SH "SYNOPSIS"
\fBlfsappearance
.br
lfsbackdropprefs
.br
lfsdesktopprefs
.br
lfstkprefs
.br
lfswmprefs\fR
.br
.SH "DESCRIPTION"
\fBLFSApplications\fR - Various apps for the LFS Desktop project here:
.br

http://www.linuxquestions.org/questions/linux-from-scratch-13/the-linux-from-scratch-desktop-project-4175542914
.br

Supplies:
.br

\fBlfsappearance
.br
lfsbackdropprefs
.br
lfsdesktopprefs
.br
lfstkprefs
.br
lfswmprefs\fR
.br

All GUI apps for setting prefs no command line args needed.
.br
.SH "REPORTING BUGS"
Report bugs to keithdhedger@gmail.com
.br
