LFSToolKit: LFSTK_fontDialogClass::buildDialog
apply
boldcheck
buildDialog
buildFontString
cancel
dialog
fontData
fontlist
fontname
fontsAZ
fontsize
italiccheck
labelLst
LFSTK_fontDialogClass
LFSTK_fontDialogClass
LFSTK_getFontData
LFSTK_showDialog
loadFontStrings
mainLoop
maxFonts
preview
selectedFontNumber
seperator
size
~LFSTK_fontDialogClass
buildDialog()
void LFSTK_fontDialogClass::buildDialog (void) private
Definition at line 185 of file LFSTKFontDialog.cpp.
References apply, LFSTK_windowClass::autoLabelColour, BEVELNONE, boldcheck, BORDER, BUTTONGRAV, gadgetStruct::buttonTile, cancel, CHECKBOXSIZE, LFSTK_windowClass::closeDisplayOnExit, gadgetStruct::colour, dialog, DIALOGHITE, DIALOGWIDTH, fontlist, fontsAZ, fontsize, LFSTK_gadgetClass::gadgetDetails, GADGETHITE, GADGETWIDTH, listLabelStruct::imageType, italiccheck, listLabelStruct::label, labelLst, LFSTK_windowClass::LFSTK_clearWindow(), LFSTK_windowClass::LFSTK_reloadGlobals(), LFSTK_windowClass::LFSTK_resizeWindow(), LFSTK_gadgetClass::LFSTK_setCallBack(), LFSTK_listGadgetClass::LFSTK_setList(), LFSTK_buttonClass::LFSTK_setStyle(), loadFontStrings(), maxFonts, NORMALCOLOUR, NOTHUMB, preview, select(), seperator, size, LFSTK_windowClass::windowColourNames, and YSPACING.
Referenced by LFSTK_fontDialogClass().