LFSToolKit: LFSTK_menuItemClass::LFSTK_menuItemClass
LFSTK_menuItemClass
LFSTK_menuItemClass
menu
menuData
mouseEnter
mouseExit
subwc
~LFSTK_menuItemClass
LFSTK_menuItemClass() [2/2]
LFSTK_menuItemClass::LFSTK_menuItemClass (LFSTK_toolWindowClass * parentwc, LFSTK_menuClass * mainmenu, int x, int y, unsigned w, unsigned h, menuStruct * menu, int labelgrav = LEFT)
Main Label constructor.
Parameters
parentwc Main parent window class.
x X pos.
y Y pos.
w Width.
h Height.
menu menuStruct array.
Note
optional, label gravity defaults to LEFT.
gadget gravity defaults to NorthWestGravity.
Definition at line 38 of file LFSTKMenuItem.cpp.
References BEVELNONE, BUTTONGRAV, LFSTK_gadgetClass::colourNames, LFSTK_gadgetClass::cr, DISCLOSURE, LFSTK_gadgetClass::display, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, menuStruct::hasSubMenu, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_lib::LFSTK_getUseTheme(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_gadgetClass::LFSTK_setFontColourName(), LFSTK_gadgetClass::LFSTK_setFontString(), LFSTK_gadgetClass::LFSTK_setLabelGravity(), LFSTK_gadgetClass::LFSTK_setTile(), menu, menuData, MENUITEMGADGET, LFSTK_gadgetClass::ml, NORMALCOLOUR, LFSTK_gadgetClass::pad, LFSTK_gadgetClass::parent, LFSTK_gadgetClass::sfc, LFSTK_gadgetClass::style, TRIANGLESIZE, mappedListener::type, TYPEMENUITEMFONT, TYPEMENUITEMFONTCOLOUR, TYPEMENUITEMTILE, LFSTK_gadgetClass::useTile, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, and LFSTK_gadgetClass::window.