LFSToolKit: LFSTK_listGadgetClass::LFSTK_setListFromFile
currentItem
data
freeCairoImages
freeList
keyRelease
labels
LFSTK_appendToList
LFSTK_freeList
LFSTK_getCurrentListItem
LFSTK_getSelectedLabel
LFSTK_listGadgetClass
LFSTK_setListFromFile
LFSTK_updateList
listCntNew
listDataArray
listOffset
maxShowing
mouseDown
mouseEnter
mouseExit
mouseUp
scrollBar
scrollCB
scrollListCB
select
selectKey
setCurrentItem
setNavSensitive
~LFSTK_listGadgetClass
LFSTK_setListFromFile()
void LFSTK_listGadgetClass::LFSTK_setListFromFile (const char * filepath, bool includeempty)
Set new list from contents of file.
Parameters
list const char * file path.
Note
Passing NULL dletes current list.
Definition at line 100 of file LFSTKListGadget.cpp.
References freeList(), LFSTK_windowClass::globalLib, listLabelStruct::imageType, listLabelStruct::label, LFSTK_appendToList(), LFSTK_lib::LFSTK_oneLiner(), LFSTK_updateList(), NOTHUMB, listLabelStruct::userData, and LFSTK_gadgetClass::wc.