LFSToolKit: LFSTK_imageClass::LFSTK_imageClass
LFSTK_clearWindow
LFSTK_imageClass
LFSTK_imageClass
mouseUp
shape
shapecr
shapesfc
~LFSTK_imageClass
LFSTK_imageClass() [2/2]
LFSTK_imageClass::LFSTK_imageClass (LFSTK_windowClass * parentwc, const char * imagepath, int x, int y, unsigned w, unsigned h, int gravity, bool scale)
Main button constructor.
Parameters
parentwc Main parent window class.
imagepath Path to image.
x X pos.
y Y pos.
w Width.
gravity Button gravity.
Definition at line 116 of file LFSTKImage.cpp.
References BEVELNONE, LFSTK_gadgetClass::cr, LFSTK_gadgetClass::display, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gadgetGeom, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, geometryStruct::h, IMAGEGADGET, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_gadgetClass::LFSTK_setImageFromPath(), LFSTK_gadgetClass::ml, NOINDICATOR, NORMALCOLOUR, LFSTK_gadgetClass::parent, LFSTK_gadgetClass::sfc, shape, shapecr, shapesfc, mappedListener::type, LFSTK_windowClass::useTile, LFSTK_gadgetClass::useTile, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, LFSTK_gadgetClass::window, and LFSTK_windowClass::windowColourNames.