LFSToolKit: LFSTK_fontDialogClass::LFSTK_showDialog
apply
boldcheck
buildDialog
buildFontString
cancel
dialog
fontData
fontlist
fontname
fontsAZ
fontsize
italiccheck
LFSTK_fontDialogClass
LFSTK_fontDialogClass
LFSTK_getFontData
LFSTK_showDialog
loadFontStrings
mainLoop
maxFonts
preview
selectedFontNumber
seperator
size
~LFSTK_fontDialogClass
LFSTK_showDialog()
bool LFSTK_fontDialogClass::LFSTK_showDialog (const char * font)
Definition at line 151 of file LFSTKFontDialog.cpp.
References dialog, LFSTK_windowClass::display, fontData, mappedListener::function, mappedListener::gadget, fontDataStruct::isValid, LFSTK_getFontData(), LFSTK_windowClass::LFSTK_getMappedListener(), LFSTK_windowClass::LFSTK_handleWindowEvents(), LFSTK_windowClass::LFSTK_hideWindow(), LFSTK_windowClass::LFSTK_setKeepAbove(), LFSTK_windowClass::LFSTK_setTransientFor(), LFSTK_windowClass::LFSTK_showWindow(), mainLoop, LFSTK_gadgetClass::ml, mappedListener::type, LFSTK_gadgetClass::wc, and LFSTK_windowClass::window.