LFSToolKit: LFSTK_labelClass::LFSTK_labelClass
LFSTK_labelClass
LFSTK_labelClass
mouseDown
mouseEnter
mouseExit
mouseUp
~LFSTK_labelClass
LFSTK_labelClass() [2/2]
LFSTK_labelClass::LFSTK_labelClass (LFSTK_windowClass * parentwc, const char * label, int x, int y, unsigned w, unsigned h, int gravity = CENTRE, int bgrav = BUTTONGRAV)
Main Label constructor.
Parameters
parentwc Main parent window class.
label Displayed name.
x X pos.
y Y pos.
w Width.
h Height.
gravity Label gravity
Note
optional, label gravity defaults to CENTRE.
gadget gravity defaults to NorthWestGravity.
Definition at line 40 of file LFSTKLabel.cpp.
References BEVELNONE, LFSTK_gadgetClass::cr, LFSTK_gadgetClass::display, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, LFSTK_gadgetClass::label, LABELGADGET, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_lib::LFSTK_getUseTheme(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_gadgetClass::LFSTK_setFontColourName(), LFSTK_gadgetClass::LFSTK_setLabelGravity(), LFSTK_gadgetClass::LFSTK_setTile(), LFSTK_gadgetClass::ml, NOINDICATOR, NORMALCOLOUR, LFSTK_gadgetClass::parent, LFSTK_gadgetClass::sfc, LFSTK_gadgetClass::style, mappedListener::type, TYPEFONTCOLOUR, TYPEWINDOWTILE, LFSTK_gadgetClass::useTile, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, LFSTK_gadgetClass::window, and LFSTK_windowClass::windowColourNames.