LFSToolKit: LFSTK_scrollBarClass::LFSTK_clearWindow
downRight
LFSTK_clearWindow
LFSTK_getValue
LFSTK_scrollBarClass
LFSTK_scrollBarClass
LFSTK_scrollByLine
LFSTK_scrollByPage
LFSTK_setLineScroll
LFSTK_setPageScroll
LFSTK_setScale
LFSTK_setStyle
LFSTK_setValue
lineScroll
lineUpDown
maxScale
maxValue
minScale
mouseDown
mouseEnter
mouseExit
mouseUp
pageScroll
pageUpDown
reverse
scale
setState
startDrag
startThumbDrag
thumb
thumbClicked
upLeft
value
verticalBar
~LFSTK_scrollBarClass
LFSTK_clearWindow()
void LFSTK_scrollBarClass::LFSTK_clearWindow (void) virtual
Clear the gadget window to the appropriate state.
Reimplemented from LFSTK_gadgetClass.
Definition at line 239 of file LFSTKScrollBar.cpp.
References LFSTK_gadgetClass::callback, LFSTK_gadgetClass::clearBox(), LFSTK_gadgetClass::display, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::LFSTK_clearWindow(), buttonCB::releaseCallback, setState(), startDrag, thumb, and buttonCB::userData.
Referenced by setState().