LFSToolKit: LFSTK_toggleButtonClass::LFSTK_toggleButtonClass
boxStyle
checkOff
checkOn
LFSTK_getValue
LFSTK_setToggleStyle
LFSTK_setValue
LFSTK_toggleButtonClass
LFSTK_toggleButtonClass
mouseDown
mouseEnter
mouseExit
mouseUp
toggleState
~LFSTK_toggleButtonClass
LFSTK_toggleButtonClass() [2/2]
LFSTK_toggleButtonClass::LFSTK_toggleButtonClass (LFSTK_windowClass * parentwc, const char * label, int x, int y, unsigned w, unsigned h, int gravity)
Main button constructor.
Parameters
parentwc Main parent window class.
label Displayed name.
x X pos.
y Y pos.
w Width.
h Height.
gravity Button gravity.
Definition at line 49 of file LFSTKToggleButton.cpp.
References BEVELNONE, BEVELOUT, boxStyle, CHECK, CHECKBOXSIZE, checkOff, checkOn, LFSTK_gadgetClass::cImage, LFSTK_gadgetClass::cr, LFSTK_gadgetClass::display, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gadgetGeom, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, geometryStruct::h, LFSTK_gadgetClass::label, LFSTK_gadgetClass::labelOffset, LEFT, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_createSurfaceFromPath(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_lib::LFSTK_getThemePath(), LFSTK_lib::LFSTK_getUseTheme(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_gadgetClass::LFSTK_setFontColourName(), LFSTK_gadgetClass::LFSTK_setLabelGravity(), LFSTK_gadgetClass::LFSTK_setTile(), LFSTK_gadgetClass::ml, NORMALCOLOUR, LFSTK_gadgetClass::parent, LFSTK_gadgetClass::sfc, LFSTK_gadgetClass::showIndicator, LFSTK_gadgetClass::style, TOGGLECHECK, TOGGLEGADGET, toggleState, mappedListener::type, TYPEBUTTONTILE, TYPEFONTCOLOUR, LFSTK_gadgetClass::useImage, LFSTK_gadgetClass::useTile, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, LFSTK_gadgetClass::window, and LFSTK_windowClass::windowColourNames.