LFSToolKit: LFSTK_menuItemClass::mouseEnter
LFSTK_menuItemClass
LFSTK_menuItemClass
menu
menuData
mouseEnter
mouseExit
subwc
~LFSTK_menuItemClass
mouseEnter()
bool LFSTK_menuItemClass::mouseEnter (XButtonEvent * e) virtual
Mouse enter callback.
Parameters
e XButtonEvent passed from mainloop->listener.
Returns
Return true if event fully handeled or false to pass it on.
Reimplemented from LFSTK_gadgetClass.
Definition at line 98 of file LFSTKMenuItem.cpp.
References gadgetStruct::bevel, BEVELOUT, CAIROTHUMB, LFSTK_gadgetClass::callback, gadgetStruct::colour, LFSTK_gadgetClass::colourNames, menuStruct::data, LFSTK_windowClass::display, LFSTK_gadgetClass::display, FILETHUMB, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gadgetGeom, GADGETHITE, menuStruct::hasSubMenu, buttonCB::ignoreCallback, menuStruct::imageData::imagePath, menuStruct::imageType, LFSTK_gadgetClass::inWindow, LFSTK_gadgetClass::isActive, LFSTK_gadgetClass::label, menuStruct::label, LEFT, LFSTK_gadgetClass::LFSTK_clearWindow(), LFSTK_windowClass::LFSTK_getMappedListener(), LFSTK_menuClass::LFSTK_getTextWidthForFont(), LFSTK_windowClass::LFSTK_handleWindowEvents(), LFSTK_windowClass::LFSTK_hideWindow(), LFSTK_menuItemClass(), LFSTK_windowClass::LFSTK_moveWindow(), LFSTK_windowClass::LFSTK_showWindow(), LFSTK_menuClass::mainLoop, LFSTK_windowClass::mainLoop, LFSTK_menuClass::mainMenuWindow, menu, MENU, menuData, LFSTK_gadgetClass::ml, mouseExit(), NOTHUMB, LFSTK_gadgetClass::pad, PRELIGHTCOLOUR, buttonCB::pressCallback, LFSTK_windowClass::rootWindow, SEPARATORHITE, gadgetStruct::state, menuStruct::subMenuCnt, menuStruct::subMenus, subwc, LFSTK_menuClass::subwindows, menuStruct::imageData::surface, mappedListener::type, geometryStruct::w, LFSTK_gadgetClass::wc, LFSTK_windowClass::window, LFSTK_gadgetClass::window, and geometryStruct::x.