LFSToolKit: LFSTK_fontDialogClass::LFSTK_fontDialogClass
apply
boldcheck
buildDialog
buildFontString
cancel
dialog
fontData
fontlist
fontname
fontsAZ
fontsize
italiccheck
LFSTK_fontDialogClass
LFSTK_fontDialogClass
LFSTK_getFontData
LFSTK_showDialog
loadFontStrings
mainLoop
maxFonts
preview
selectedFontNumber
seperator
size
~LFSTK_fontDialogClass
LFSTK_fontDialogClass() [2/2]
LFSTK_fontDialogClass::LFSTK_fontDialogClass (LFSTK_windowClass * parentwc, const char * label, int x, int y, unsigned w, unsigned h, int gravity)
Main button constructor.
Parameters
parentwc Main parent window class.
label Displayed name.
x X pos.
y Y pos.
w Width.
h Height.
gravity Button gravity.
Definition at line 279 of file LFSTKFontDialog.cpp.
References BEVELOUT, fontDataStruct::bold, buildDialog(), BUTTONGADGET, LFSTK_gadgetClass::colourNames, LFSTK_gadgetClass::cr, LFSTK_gadgetClass::display, fontData, fontDataStruct::fontName, fontDataStruct::fontString, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, fontDataStruct::isValid, fontDataStruct::italic, LFSTK_gadgetClass::label, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_lib::LFSTK_getUseTheme(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_gadgetClass::LFSTK_setTile(), LFSTK_gadgetClass::ml, NOINDICATOR, NORMALCOLOUR, LFSTK_gadgetClass::parent, LFSTK_gadgetClass::sfc, mappedListener::type, TYPEBUTTONTILE, LFSTK_gadgetClass::useTile, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, and LFSTK_gadgetClass::window.