LFSToolKit: LFSTK_lib::LFSTK_getGlobalString
autoLabelColour
bestFontColour
cairo_image_surface_create_from_jpeg_mem
globalButtonColours
globalButtonTile
globalCursorColour
globalFontColourNames
globalFontString
globalListTroughColour
globalMenuItemColours
globalMenuItemFontColourNames
globalMenuItemFontString
globalMenuItemTile
globalMonoFontString
globalSBTroughColour
globalWindowColours
globalWindowTile
LFSTK_cairo_image_surface_create_from_jpeg
LFSTK_createSurfaceFromPath
LFSTK_findThemedIcon
LFSTK_gadgetEvent
LFSTK_getAutoLabelColour
LFSTK_getColourFromName
LFSTK_getGlobalString
LFSTK_getMimeType
LFSTK_getThemePath
LFSTK_getTKArgs
LFSTK_getUseTheme
LFSTK_getWindowPixmap
LFSTK_lib
LFSTK_loadVarsFromFile
LFSTK_oneLiner
LFSTK_pointInRect
LFSTK_saveVarsToFile
LFSTK_setAutoLabelColour
LFSTK_setCairoSurface
LFSTK_setColourFromName
LFSTK_setGlobalString
LFSTK_setThemePath
LFSTK_setUseTheme
lfsToolKitGlobals
themePath
useTheme
~LFSTK_lib
LFSTK_getGlobalString()
const char * LFSTK_lib::LFSTK_getGlobalString (int state, int type)
Gets a global string or the default.
Parameters
state Gadget state.
type Type of string to get.
Note
type=TYPEWINDOW=0,TYPEBUTTON,TYPEMENUITEM,TYPEFONTCOLOUR,TYPEMENUITEMFONTCOLOUR,TYPEMENUITEMFONT,TYPEFONT
Returns
const char* String.
Note
Don't free return value.
If global string not loaded return default.
Definition at line 201 of file LFSTKLib.cpp.
References defaultButtonTile, defaultColourStrings, defaultCursorColour, defaultFontColourStrings, defaultFontString, defaultMenuItemTile, defaultMonoFontString, defaultWindowTile, globalButtonColours, globalButtonTile, globalCursorColour, globalFontColourNames, globalFontString, globalListTroughColour, globalMenuItemColours, globalMenuItemFontColourNames, globalMenuItemFontString, globalMenuItemTile, globalMonoFontString, globalSBTroughColour, globalWindowColours, globalWindowTile, TYPEBUTTON, TYPEBUTTONTILE, TYPECURSORCOLOUR, TYPEFONT, TYPEFONTCOLOUR, TYPELISTTROUGHCOLOUR, TYPEMENUITEM, TYPEMENUITEMFONT, TYPEMENUITEMFONTCOLOUR, TYPEMENUITEMTILE, TYPEMONOFONT, TYPESBTROUGHCOLOUR, TYPEWINDOW, and TYPEWINDOWTILE.
Referenced by LFSTK_gadgetClass::initGadget(), LFSTK_buttonClass::LFSTK_buttonClass(), LFSTK_fontDialogClass::LFSTK_fontDialogClass(), LFSTK_labelClass::LFSTK_labelClass(), LFSTK_lineEditClass::LFSTK_lineEditClass(), LFSTK_listGadgetClass::LFSTK_listGadgetClass(), LFSTK_menuClass::LFSTK_menuClass(), LFSTK_menuItemClass::LFSTK_menuItemClass(), LFSTK_multiLineEditClass::LFSTK_multiLineEditClass(), LFSTK_gadgetClass::LFSTK_reloadColours(), LFSTK_scrollBarClass::LFSTK_scrollBarClass(), LFSTK_toggleButtonClass::LFSTK_toggleButtonClass(), LFSTK_windowClass::loadGlobalColours(), LFSTK_listGadgetClass::select(), LFSTK_toolWindowClass::windowClassInitCommon(), and LFSTK_windowClass::windowClassInitCommon().