LFSToolKit: LFSTK_multiLineEditClass::LFSTK_multiLineEditClass
buffer
clientMessage
cursorPos
drawText
getClip
gotFocus
isFocused
keyRelease
LFSTK_clearWindow
LFSTK_dropData
LFSTK_getBuffer
LFSTK_getCStr
LFSTK_multiLineEditClass
LFSTK_multiLineEditClass
LFSTK_resizeWindow
LFSTK_setBuffer
LFSTK_setFocus
LFSTK_setFormatedText
lines
lostFocus
setDisplayLines
topLine
~LFSTK_multiLineEditClass
LFSTK_multiLineEditClass() [2/2]
LFSTK_multiLineEditClass::LFSTK_multiLineEditClass (LFSTK_windowClass * parentwc, const char * label, int x, int y, unsigned w, unsigned h, int gravity)
Main line edit constructor.
Parameters
parentwc Main parent window class.
label Displayed name.
x X pos.
y Y pos.
w Width.
h Height.
gravity Button gravity.
Definition at line 62 of file LFSTKMultiLineEdit.cpp.
References BEVELIN, buffer, LFSTK_gadgetClass::colourNames, LFSTK_gadgetClass::cr, cursorPos, LFSTK_gadgetClass::display, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetAcceptsDnD, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, LFSTK_gadgetClass::inWindow, isFocused, LFSTK_gadgetClass::label, LFSTK_gadgetClass::labelGravity, LEFT, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_windowClass::LFSTK_initDnD(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setColourName(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_lineEditClass::LFSTK_setCursorColourName(), LFSTK_gadgetClass::LFSTK_setFontColourName(), LFSTK_gadgetClass::LFSTK_setFontString(), LFSTK_gadgetClass::ml, LFSTK_gadgetClass::monoFontString, MULTILINEGADGET, NOINDICATOR, NORMALCOLOUR, LFSTK_gadgetClass::parent, setDisplayLines(), LFSTK_gadgetClass::sfc, topLine, mappedListener::type, TYPECURSORCOLOUR, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, and LFSTK_gadgetClass::window.