LFSToolKit: LFSTK_multiLineEditClass::setDisplayLines
buffer
clientMessage
cursorPos
drawText
getClip
gotFocus
isFocused
keyRelease
LFSTK_clearWindow
LFSTK_dropData
LFSTK_getBuffer
LFSTK_getCStr
LFSTK_multiLineEditClass
LFSTK_multiLineEditClass
LFSTK_resizeWindow
LFSTK_setBuffer
LFSTK_setFocus
LFSTK_setFormatedText
lines
lostFocus
setDisplayLines
topLine
~LFSTK_multiLineEditClass
setDisplayLines()
void LFSTK_multiLineEditClass::setDisplayLines (void) private
Set up lines for display.
Definition at line 534 of file LFSTKMultiLineEdit.cpp.
References buffer, LFSTK_gadgetClass::cr, lineStruct::cursorPos, cursorPos, LFSTK_gadgetClass::fontName, LFSTK_gadgetClass::fontSize, lineStruct::height, isFocused, LFSTK_clearWindow(), LFSTK_gadgetClass::LFSTK_getGeom(), lineStruct::line, lines, LFSTK_gadgetClass::slant, geometryStruct::w, LFSTK_gadgetClass::weight, lineStruct::width, lineStruct::xpos, and lineStruct::ypos.
Referenced by gotFocus(), keyRelease(), LFSTK_multiLineEditClass(), LFSTK_setFocus(), LFSTK_setFormatedText(), and lostFocus().