LFSToolKit: LFSTK_fontDialogClass::LFSTK_getFontData
apply
boldcheck
buildDialog
buildFontString
cancel
dialog
fontData
fontlist
fontname
fontsAZ
fontsize
italiccheck
labelLst
LFSTK_fontDialogClass
LFSTK_fontDialogClass
LFSTK_getFontData
LFSTK_showDialog
loadFontStrings
mainLoop
maxFonts
preview
selectedFontNumber
seperator
size
~LFSTK_fontDialogClass
LFSTK_getFontData()
const fontDataStruct * LFSTK_fontDialogClass::LFSTK_getFontData (bool rebuild)
Get pointer to font data.
Parameters
bool rebuild
Returns
const pointer to structure.
Note
private data do NOT alter/free
Definition at line 84 of file LFSTKFontDialog.cpp.
References buildFontString(), and fontData.
Referenced by checkCB(), LFSTK_showDialog(), and select().