LFSToolKit: LFSTK_toolWindowClass::windowClassInitCommon
LFSTK_toolWindowClass
LFSTK_toolWindowClass
windowClassInitCommon
~LFSTK_toolWindowClass
windowClassInitCommon()
void LFSTK_toolWindowClass::windowClassInitCommon (windowInitStruct * wi) private
Common window constructor.
Parameters
windowInitStruct *wi.
Note
wi contains startup window params.
Definition at line 32 of file LFSTKToolWindow.cpp.
References ABOVEALL, LFSTK_windowClass::acceptDnd, BELOWALL, LFSTK_windowClass::closeDisplayOnExit, LFSTK_windowClass::cm, LFSTK_windowClass::configDir, LFSTK_windowClass::cr, windowInitStruct::decorated, DEFAULTFONT, LFSTK_windowClass::depth, LFSTK_windowClass::display, windowInitStruct::display, LFSTK_windowClass::fontString, LFSTK_windowClass::gadgetMap, LFSTK_windowClass::gc, LFSTK_windowClass::globalLib, windowInitStruct::h, LFSTK_windowClass::initWindow(), LFSTK_windowClass::isActive, windowInitStruct::level, LFSTK_lib::LFSTK_getGlobalString(), LFSTK_lib::LFSTK_getUseTheme(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_windowClass::LFSTK_setDecorated(), LFSTK_windowClass::LFSTK_setFontString(), LFSTK_windowClass::LFSTK_setTile(), LFSTK_windowClass::LFSTK_setWindowType(), LFSTK_windowClass::loadMonitorData(), windowInitStruct::loadVars, windowInitStruct::name, windowInitStruct::overRide, LFSTK_windowClass::rootWindow, LFSTK_windowClass::screen, LFSTK_windowClass::setWindowGeom(), LFSTK_windowClass::sfc, windowInitStruct::shutDisplayOnExit, TYPEWINDOWTILE, LFSTK_windowClass::userHome, LFSTK_windowClass::useTile, LFSTK_windowClass::visual, windowInitStruct::w, LFSTK_windowClass::window, LFSTK_windowClass::windowName, windowInitStruct::windowType, WINDSETALL, windowInitStruct::x, and windowInitStruct::y.
Referenced by LFSTK_toolWindowClass().