LFSToolKit: LFSTK_lineEditClass::LFSTK_lineEditClass
buffer
charWidth
clientMessage
cursorColour
cursorPos
drawLabel
getClip
gotFocus
isFocused
keyRelease
keysym_return
LFSTK_clearWindow
LFSTK_dropData
LFSTK_getBuffer
LFSTK_getCStr
LFSTK_getKey
LFSTK_getKeySym
LFSTK_getModifier
LFSTK_lineEditClass
LFSTK_lineEditClass
LFSTK_resizeWindow
LFSTK_setBuffer
LFSTK_setCursorColourName
LFSTK_setFocus
LFSTK_setFormatedText
lostFocus
mouseDown
mouseEnter
offsetCurs
setOffsetcurs
state
visCursorPos
~LFSTK_lineEditClass
LFSTK_lineEditClass() [2/2]
LFSTK_lineEditClass::LFSTK_lineEditClass (LFSTK_windowClass * parentwc, const char * label, int x, int y, unsigned w, unsigned h, int gravity)
Main line edit constructor.
Parameters
parentwc Main parent window class.
label Displayed name.
x X pos.
y Y pos.
w Width.
h Height.
gravity Button gravity.
Definition at line 50 of file LFSTKLineEdit.cpp.
References BEVELIN, charWidth, LFSTK_gadgetClass::colourNames, LFSTK_gadgetClass::cr, LFSTK_gadgetClass::display, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetAcceptsDnD, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, LFSTK_gadgetClass::inWindow, isFocused, LFSTK_gadgetClass::label, LFSTK_gadgetClass::labelGravity, LEFT, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_gadgetClass::LFSTK_getTextRealWidth(), LFSTK_windowClass::LFSTK_initDnD(), LFSTK_setBuffer(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setColourName(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_setCursorColourName(), LFSTK_gadgetClass::LFSTK_setFontColourName(), LFSTK_gadgetClass::LFSTK_setFontString(), LINEEDITGADGET, LFSTK_gadgetClass::ml, LFSTK_gadgetClass::monoFontString, NOINDICATOR, NORMALCOLOUR, LFSTK_gadgetClass::parent, LFSTK_gadgetClass::sfc, mappedListener::type, TYPECURSORCOLOUR, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, and LFSTK_gadgetClass::window.