LFSToolKit: LFSTK_lineEditClass::drawLabel
buffer
charWidth
clientMessage
cursorColour
cursorPos
drawLabel
getClip
gotFocus
isFocused
keyRelease
keysym_return
LFSTK_clearWindow
LFSTK_dropData
LFSTK_getBuffer
LFSTK_getCStr
LFSTK_getKey
LFSTK_getKeySym
LFSTK_getModifier
LFSTK_lineEditClass
LFSTK_lineEditClass
LFSTK_resizeWindow
LFSTK_setBuffer
LFSTK_setCursorColourName
LFSTK_setFocus
LFSTK_setFormatedText
lostFocus
mouseDown
mouseEnter
offsetCurs
setOffsetcurs
state
visCursorPos
~LFSTK_lineEditClass
drawLabel()
void LFSTK_lineEditClass::drawLabel (void) private
Definition at line 235 of file LFSTKLineEdit.cpp.
References buffer, LFSTK_gadgetClass::colourNames, LFSTK_gadgetClass::cr, cursorColour, cursorPos, LFSTK_gadgetClass::fontName, LFSTK_gadgetClass::fontSize, cairoColor::g, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gadgetGeom, gadgetStruct::gadgetGeom, geometryStruct::h, isFocused, LFSTK_gadgetClass::LFSTK_getTextRealWidth(), LFSTK_gadgetClass::LFSTK_getTextWidth(), NORMALCOLOUR, offsetCurs, LFSTK_gadgetClass::pad, cairoColor::r, colourStruct::RGBAColour, LFSTK_gadgetClass::slant, LFSTK_gadgetClass::textExtents, geometryStruct::w, and LFSTK_gadgetClass::weight.
Referenced by LFSTK_clearWindow().