LFSToolKit: LFSTK_lineEditClass::LFSTK_getCStr
buffer
charWidth
clientMessage
cursorColour
cursorPos
drawLabel
getClip
gotFocus
isFocused
keyRelease
keysym_return
LFSTK_clearWindow
LFSTK_dropData
LFSTK_getBuffer
LFSTK_getCStr
LFSTK_getKey
LFSTK_getKeySym
LFSTK_getModifier
LFSTK_lineEditClass
LFSTK_lineEditClass
LFSTK_resizeWindow
LFSTK_setBuffer
LFSTK_setCursorColourName
LFSTK_setFocus
LFSTK_setFormatedText
lostFocus
mouseDown
mouseEnter
offsetCurs
setOffsetcurs
state
visCursorPos
~LFSTK_lineEditClass
LFSTK_getCStr()
const char * LFSTK_lineEditClass::LFSTK_getCStr (void)
Return the contents of the gadget.
Returns
Return's a c str.
Note
Don't free the returned string.
Definition at line 230 of file LFSTKLineEdit.cpp.
References buffer.
Referenced by LFSTK_fontDialogClass::buildFontString(), LFSTK_fileDialogClass::LFSTK_showFileDialog(), LFSTK_fileDialogClass::select(), LFSTK_fileDialogClass::setFileData(), and LFSTK_fileDialogClass::setPreviewData().