LFSToolKit: LFSTK_lib::LFSTK_setCairoSurface
autoLabelColour
bestFontColour
cairo_image_surface_create_from_jpeg_mem
globalButtonColours
globalButtonTile
globalCursorColour
globalFontColourNames
globalFontString
globalListTroughColour
globalMenuItemColours
globalMenuItemFontColourNames
globalMenuItemFontString
globalMenuItemTile
globalMonoFontString
globalSBTroughColour
globalWindowColours
globalWindowTile
LFSTK_cairo_image_surface_create_from_jpeg
LFSTK_createSurfaceFromPath
LFSTK_findThemedIcon
LFSTK_gadgetEvent
LFSTK_getAutoLabelColour
LFSTK_getColourFromName
LFSTK_getGlobalString
LFSTK_getMimeType
LFSTK_getThemePath
LFSTK_getTKArgs
LFSTK_getUseTheme
LFSTK_getWindowPixmap
LFSTK_lib
LFSTK_loadVarsFromFile
LFSTK_oneLiner
LFSTK_pointInRect
LFSTK_saveVarsToFile
LFSTK_setAutoLabelColour
LFSTK_setCairoSurface
LFSTK_setColourFromName
LFSTK_setGlobalString
LFSTK_setThemePath
LFSTK_setUseTheme
lfsToolKitGlobals
themePath
useTheme
~LFSTK_lib
LFSTK_setCairoSurface()
void LFSTK_lib::LFSTK_setCairoSurface (Display * display, Window window, Visual * visual, cairo_surface_t ** sfc, cairo_t ** cr, int width, int height)
Set cairo surface and context for window.
Parameters
Display* display.
Window window.
Visual visual.
cairo_surface_t **sfc.
cairo_t **cr.
int width.
int height.
Definition at line 881 of file LFSTKLib.cpp.
Referenced by LFSTK_buttonClass::LFSTK_buttonClass(), LFSTK_fontDialogClass::LFSTK_fontDialogClass(), LFSTK_menuClass::LFSTK_getTextWidthForFont(), LFSTK_windowClass::LFSTK_handleWindowEvents(), LFSTK_imageClass::LFSTK_imageClass(), LFSTK_labelClass::LFSTK_labelClass(), LFSTK_lineEditClass::LFSTK_lineEditClass(), LFSTK_listGadgetClass::LFSTK_listGadgetClass(), LFSTK_menuItemClass::LFSTK_menuItemClass(), LFSTK_multiLineEditClass::LFSTK_multiLineEditClass(), LFSTK_windowClass::LFSTK_resizeWindow(), LFSTK_scrollBarClass::LFSTK_scrollBarClass(), LFSTK_gadgetClass::LFSTK_setGadgetSize(), LFSTK_toggleButtonClass::LFSTK_toggleButtonClass(), LFSTK_toolWindowClass::windowClassInitCommon(), and LFSTK_windowClass::windowClassInitCommon().