LFSToolKit: LFSTK_listGadgetClass::select
currentItem
data
freeCairoImages
freeList
keyRelease
labelData
labels
LFSTK_getCurrentListItem
LFSTK_getSelectedLabel
LFSTK_listGadgetClass
LFSTK_setList
LFSTK_setListFromFile
listCnt
listOffset
maxShowing
mouseDown
mouseEnter
mouseExit
mouseUp
scrollBar
scrollCB
scrollListCB
select
selectKey
setCurrentItem
setNavSensitive
~LFSTK_listGadgetClass
select()
bool LFSTK_listGadgetClass::select (void * object, void * userdata) static private
Definition at line 33 of file LFSTKListGadget.cpp.
References ACTIVECOLOUR, LFSTK_gadgetClass::callback, currentItem, LFSTK_windowClass::globalLib, LFSTK_gadgetClass::isDoubleClick, LFSTK_gadgetClass::label, labels, LFSTK_gadgetClass::LFSTK_clearWindow(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_scrollBarClass::LFSTK_scrollByLine(), LFSTK_gadgetClass::LFSTK_setColourName(), listOffset, listData::mainObject, maxShowing, LFSTK_gadgetClass::mouseUpEvent, NORMALCOLOUR, buttonCB::releaseCallback, scrollBar, setCurrentItem(), TYPELISTTROUGHCOLOUR, buttonCB::userData, listData::userData, and LFSTK_gadgetClass::wc.
Referenced by LFSTK_listGadgetClass().