LFSToolKit: LFSTK_scrollBarClass::LFSTK_scrollBarClass
downRight
LFSTK_clearWindow
LFSTK_getValue
LFSTK_scrollBarClass
LFSTK_scrollBarClass
LFSTK_scrollByLine
LFSTK_scrollByPage
LFSTK_setLineScroll
LFSTK_setPageScroll
LFSTK_setScale
LFSTK_setStyle
LFSTK_setValue
lineScroll
lineUpDown
maxScale
maxValue
minScale
mouseDown
mouseEnter
mouseExit
mouseUp
pageScroll
pageUpDown
reverse
scale
setState
startDrag
startThumbDrag
thumb
thumbClicked
upLeft
value
verticalBar
~LFSTK_scrollBarClass
LFSTK_scrollBarClass() [2/2]
LFSTK_scrollBarClass::LFSTK_scrollBarClass (LFSTK_windowClass * parentwc, bool vertical, int x, int y, unsigned w, unsigned h, int gravity)
Main button constructor.
Parameters
parentwc Main parent window class.
vertical True=Vertical bar, else horizontal.
x X pos.
y Y pos.
w Width.
h Height.
gravity Button gravity.
Definition at line 53 of file LFSTKScrollBar.cpp.
References BEVELOUT, CENTRE, LFSTK_gadgetClass::colourNames, LFSTK_gadgetClass::cr, LFSTK_gadgetClass::display, downRight, mappedListener::function, mappedListener::gadget, LFSTK_gadgetClass::gadgetDetails, LFSTK_gadgetClass::gc, LFSTK_windowClass::globalLib, LFSTK_windowClass::LFSTK_addMappedListener(), LFSTK_gadgetClass::LFSTK_allowXMovement(), LFSTK_gadgetClass::LFSTK_allowYMovement(), LFSTK_lib::LFSTK_gadgetEvent(), LFSTK_lib::LFSTK_getGlobalString(), LFSTK_lib::LFSTK_getThemePath(), LFSTK_gadgetClass::LFSTK_setCairoFontData(), LFSTK_lib::LFSTK_setCairoSurface(), LFSTK_gadgetClass::LFSTK_setCallBack(), LFSTK_gadgetClass::LFSTK_setCanDrag(), LFSTK_gadgetClass::LFSTK_setColourName(), LFSTK_gadgetClass::LFSTK_setCommon(), LFSTK_gadgetClass::LFSTK_setImageFromPath(), LFSTK_gadgetClass::LFSTK_setLimits(), lineUpDown(), LFSTK_gadgetClass::ml, NOINDICATOR, NORMALCOLOUR, LFSTK_gadgetClass::parent, SCROLLBARGADGET, LFSTK_gadgetClass::sfc, startThumbDrag(), thumb, thumbClicked(), mappedListener::type, TYPESBTROUGHCOLOUR, upLeft, LFSTK_gadgetClass::userData, verticalBar, LFSTK_gadgetClass::visual, LFSTK_gadgetClass::wc, and LFSTK_gadgetClass::window.