LFSToolKit: LFSTK_lib::LFSTK_gadgetEvent
autoLabelColour
bestFontColour
cairo_image_surface_create_from_jpeg_mem
globalButtonColours
globalButtonTile
globalCursorColour
globalFontColourNames
globalFontString
globalListTroughColour
globalMenuItemColours
globalMenuItemFontColourNames
globalMenuItemFontString
globalMenuItemTile
globalMonoFontString
globalSBTroughColour
globalWindowColours
globalWindowTile
LFSTK_cairo_image_surface_create_from_jpeg
LFSTK_createSurfaceFromPath
LFSTK_findThemedIcon
LFSTK_gadgetEvent
LFSTK_getAutoLabelColour
LFSTK_getColourFromName
LFSTK_getGlobalString
LFSTK_getMimeType
LFSTK_getThemePath
LFSTK_getTKArgs
LFSTK_getUseTheme
LFSTK_getWindowPixmap
LFSTK_lib
LFSTK_loadVarsFromFile
LFSTK_oneLiner
LFSTK_pointInRect
LFSTK_saveVarsToFile
LFSTK_setAutoLabelColour
LFSTK_setCairoSurface
LFSTK_setColourFromName
LFSTK_setGlobalString
LFSTK_setThemePath
LFSTK_setUseTheme
lfsToolKitGlobals
themePath
useTheme
~LFSTK_lib
LFSTK_gadgetEvent()
bool LFSTK_lib::LFSTK_gadgetEvent (void * self, XEvent * e, int type) static
Handle gadget events.
Parameters
self* Gadget.
XEvent* Pointer to Xevent from main loop.
type Gadget type.
Returns
bool Event handled.
printf("MotionNotify\n");
Definition at line 530 of file LFSTKLib.cpp.
References LFSTK_gadgetClass::currentButton, LFSTK_windowClass::dbClick, LFSTK_windowClass::display, LFSTK_gadgetClass::firstClick, LFSTK_gadgetClass::gotFocus(), geometryStruct::h, LFSTK_gadgetClass::isDoubleClick, LFSTK_gadgetClass::keyRelease(), LFSTK_gadgetClass::lastTime, LFSTK_gadgetClass::LFSTK_clearWindow(), LFSTK_gadgetClass::LFSTK_doPopUp(), LFSTK_gadgetClass::LFSTK_getContextWindow(), LFSTK_gadgetClass::LFSTK_getGlobalGeom(), LINEEDITGADGET, LFSTK_gadgetClass::lostFocus(), LFSTK_gadgetClass::mouseDown(), LFSTK_gadgetClass::mouseDrag(), LFSTK_gadgetClass::mouseEnter(), LFSTK_gadgetClass::mouseExit(), LFSTK_gadgetClass::mouseUp(), LFSTK_windowClass::popupFromGadget, geometryStruct::w, LFSTK_gadgetClass::wc, LFSTK_windowClass::window, geometryStruct::x, and geometryStruct::y.
Referenced by LFSTK_buttonClass::LFSTK_buttonClass(), LFSTK_fontDialogClass::LFSTK_fontDialogClass(), LFSTK_imageClass::LFSTK_imageClass(), LFSTK_labelClass::LFSTK_labelClass(), LFSTK_lineEditClass::LFSTK_lineEditClass(), LFSTK_listGadgetClass::LFSTK_listGadgetClass(), LFSTK_menuItemClass::LFSTK_menuItemClass(), LFSTK_multiLineEditClass::LFSTK_multiLineEditClass(), LFSTK_scrollBarClass::LFSTK_scrollBarClass(), and LFSTK_toggleButtonClass::LFSTK_toggleButtonClass().