LFSToolKit: buttonCB::pressCallback
ignoreCallback
pressCallback
releaseCallback
userData
pressCallback
bool(* buttonCB::pressCallback) (void *, void *)
Definition at line 173 of file LFSTKGlobals.h.
Referenced by LFSTK_buttonClass::keyRelease(), LFSTK_lineEditClass::keyRelease(), LFSTK_multiLineEditClass::keyRelease(), LFSTK_menuClass::LFSTK_addMainMenus(), LFSTK_menuClass::LFSTK_setCallBack(), LFSTK_gadgetClass::LFSTK_setCallBack(), LFSTK_toggleButtonClass::mouseDown(), LFSTK_gadgetClass::mouseDown(), and LFSTK_menuItemClass::mouseEnter().