LFSToolKit: mappedListener::function
function
gadget
type
function
bool(* mappedListener::function) (void *, XEvent *, int)
Definition at line 212 of file LFSTKGlobals.h.
Referenced by LFSTK_buttonClass::LFSTK_buttonClass(), LFSTK_gadgetClass::LFSTK_doPopUp(), LFSTK_fontDialogClass::LFSTK_fontDialogClass(), LFSTK_imageClass::LFSTK_imageClass(), LFSTK_labelClass::LFSTK_labelClass(), LFSTK_lineEditClass::LFSTK_lineEditClass(), LFSTK_listGadgetClass::LFSTK_listGadgetClass(), LFSTK_menuItemClass::LFSTK_menuItemClass(), LFSTK_multiLineEditClass::LFSTK_multiLineEditClass(), LFSTK_scrollBarClass::LFSTK_scrollBarClass(), LFSTK_fontDialogClass::LFSTK_showDialog(), LFSTK_fileDialogClass::LFSTK_showFileDialog(), LFSTK_menuClass::LFSTK_showMenu(), LFSTK_toggleButtonClass::LFSTK_toggleButtonClass(), and LFSTK_menuItemClass::mouseEnter().