LFSToolKit: buttonCB::releaseCallback
ignoreCallback
pressCallback
releaseCallback
userData
releaseCallback
bool(* buttonCB::releaseCallback) (void *, void *)
Definition at line 174 of file LFSTKGlobals.h.
Referenced by LFSTK_lineEditClass::keyRelease(), LFSTK_multiLineEditClass::keyRelease(), LFSTK_scrollBarClass::LFSTK_clearWindow(), LFSTK_menuClass::LFSTK_setCallBack(), LFSTK_gadgetClass::LFSTK_setCallBack(), LFSTK_imageClass::mouseUp(), LFSTK_toggleButtonClass::mouseUp(), LFSTK_gadgetClass::mouseUp(), LFSTK_listGadgetClass::select(), and LFSTK_scrollBarClass::thumbClicked().